---
# https://github.com/skpm/skpm/blob/master/.eslintrc.yml
root: true
extends:
  - airbnb-base
  - prettier
plugins:
  - no-not-accumulator-reassign
  - prettier
  - babel
env:
  node: true
rules:
  no-param-reassign: 0
  import/no-dynamic-require: 0
  no-unused-expressions: 0
  no-restricted-syntax: 1
  no-await-in-loop: 0
  no-loop-func: 0
  global-require: 0
  no-console: 0
  no-not-accumulator-reassign/no-not-accumulator-reassign: [2, ['reduce'], {props: true}]
  import/no-unresolved:
    - error
    - commonjs: true
      caseSensitive: true
      ignore:
        - '^sketch(\/|$)'
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: es5
      semi: false

# https://github.com/BohemianCoding/SketchAPI/blob/develop/.eslintrc.yml#L11
globals:
  NSFont: false
  MOPointer: false
  NSMakeRange: false
  NSMaxRange: false
  MSSelfContainedHighLevelExporter: false
  MSLayerMovement: false
  NSMakeRect: false
  MSBitmapLayer: false
  MSLayerGroup: false
  MSTextLayer: false
  MSShapeGroup: false
  NSArray: false
  NSMakePoint: false
  CGRectMake: false
  MSArtboardGroup: false
  MSPage: false
  MSApplicationMetadata: false
  log: false
  NSApplication: false
  NSDocumentController: false
  NSAlert: false
  NSComboBox: false
  NSUserDefaults: false
  AppController: false
  MSImageData: false
  NSImage: false
  MSModalInputSheet: false
  MSStyleFill: false
  MSStyleBorder: false
  MSColor: false
  MSImmutableColor: false
  MSDefaultStyle: false
  MSLayer: false
  MSDocumentData: false
  MSSymbolMaster: false
  MSSymbolInstance: false
  MSAvailableOverride: false
  MSAssetLibrary: false
  MSDocument: false
  NSURL: false
  NSSaveToOperation: false
  NSData: false
  NSDataBase64DecodingIgnoreUnknownCharacters: false
  NSPasteboard: false
  __command: false
  MSFlowConnection: false
  MSHotspotLayer: false
  NSPredicate: false
  MSRectangleShape: false
  MSSymbolMasterReference: false
  MSShareableObjectReference: false
  MSSharedStyleReference: false
  NSString: false
  MSForeignSymbolProvider: false
  MSForeignObjectCollector: false
  MSStyleShadow: false
  MSStyleInnerShadow: false
  MSGradientStop: false
  MSGradient: false
  CGPointMake: false
  MSSharedLayerReference: false
  MSSharedTextReference: false
  MSUserAssetLibrary: false
  MSRemoteAssetLibrary: false
  NSSaveAsOperation: false
  NSSaveOperation: false
  coscript: false
  __mocha__: false
  NSOpenPanel: false
  NSOKButton: false
  NSNull: false
  MSSharedLayerStyleProvider: false
  MSSharedTextStyleProvider: false
  MSForeignObjectProvider: false
  MSSharedStyle: false
  MSStyle: false
  MSDataOverride: false
  MSImmutableArtboardGroup: false
  MSImmutableLayerGroup: false
  MSImmutableHotspotLayer: false
  MSImmutableBitmapLayer: false
  MSImmutableLayer: false
  MSImmutablePage: false
  MSImmutableShapeGroup: false
  MSStyledLayer: false
  MSImmutableStyledLayer: false
  MSImmutableSymbolInstance: false
  MSImmutableSymbolMaster: false
  MSImmutableTextLayer: false
  MSImmutableDocumentData: false

parserOptions:
  sourceType: module

settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .json